### ISSUE TITLE
Threshold limit

### ISSUE THREAD

**Issue by PremTejaV** [kishan0725/The-Movie-Cinema#11]
Hey Kishan!
To Recommend movies based on the input how much similarity score you have kept as a minimum one?
How does you say whether the review is positive or negative, do you kept any threshold limit for that, can you explain it briefly?

Thank you!!

**Comment by kishan0725** [comment]
Hi Prem,
1. I'm not specifying any minimum similarity values for the recommendation. The cosine similarity algorithm provided by the sklearn package simply computes how similar the movies are. So I computed the similarity among the input movie and the movies in the dataset, sort them from high to low scores, and took the top 10 movies.
2. I have a trained model already for the sentiment analysis. So whenever a new review comes, it'll be inputted the trained model and makes decisions based on that trained model. You can tweak it when you training your model.
