### ISSUE TITLE
Error in installing requirments.txt

### ISSUE THREAD

**Issue by ajaymathur442** [kishan0725/The-Movie-Cinema#14]
![error](https://user-images.githubusercontent.com/57529648/123754753-d7345a00-d8d8-11eb-86ff-ca5eb03fa806.PNG)

**Comment by kishan0725** [comment]
There's a version conflict with the packages in the requirements.txt and the packages in your local machine. Either uninstalling the conflicted package from your machine or removing the conflicted package from the requirements.txt should do the work. Or keeping the applicating in a virtual environment can also be helpful to resolve this issue.

**Comment by ajaymathur442** [comment]
![err2](https://user-images.githubusercontent.com/57529648/123758593-b2da7c80-d8dc-11eb-96ad-ab5f73e3b7c3.PNG)
after typing movie name , enter button is not enabling   also on cmd it shows this error

**Comment by kishan0725** [comment]
The 404 favicon error has nothing to do with the application, it just the icon that will be rendered in the title bar of your browser. 

Once you type the movie name, make sure the recommend.js file gets the value of the input box.

Note: Create a new issue if you're facing any problem that's not related to this issue (Error in installing requirement.txt). Closing this issue!
