### ISSUE TITLE
I don't know how to install libraries to run this movie recommendation 

### ISSUE THREAD

**Issue by Tharun-tharun** [kishan0725/The-Movie-Cinema#15]
Hi,

I'm from Chennai and i'm a coding newbie, so this may be sort of a dumb question, i would like to use your project and need some guidance bro 

If you would make a video on it, it would be great i would like to use this project what i did is just did like the way you said
1. Cloned project
2. opened it via VScode
3. and thought of running this command like 'npm install' and 'npm run'  i thought the project will run but instead throwed me an error like this 
![image](https://user-images.githubusercontent.com/41158838/130202805-9753c3f3-6b17-4f71-992b-2f355b6cb0eb.png)

Please I need your guidance from scratch from (installing packages to running this project) even a video guide would be better if you do it from scratch

Thanks!

**Comment by kishan0725** [comment]
Follow these steps: https://github.com/kishan0725/The-Movie-Cinema#how-to-run-the-project

**Comment by Tharun-tharun** [comment]
yes bro i ran this command " pip install -r requirements.txt' tried it look at this is throwing an error 

![image](https://user-images.githubusercontent.com/41158838/130206856-78c57e05-d6bc-41fe-95f5-1fe29908ef0e.png)

**Comment by kishan0725** [comment]
There's some conflict in the package version. Try to uninstall the conflicting package and run the command or install the higher version of the same

**Comment by Tharun-tharun** [comment]
> There's some conflict in the package version. Try to uninstall the conflicting package and run the command or install the higher version of the same.
> 
> P.S - Learn fundamentals of python before proceeding with this project

Ok I'll do the same just curious to know where do you learn data science and other projects and where do you get ideas for your projects do you have any suggestions on learning the machine learning course also how did you create the website of yours and where did you take web development course. Just need your suggestion bro.

**Comment by Tharun-tharun** [comment]
bro are you there?
