### ISSUE TITLE
Not able to change to another new poster of mine 

### ISSUE THREAD

**Issue by Tharun-tharun** [kishan0725/The-Movie-Cinema#16]
I would like to make changes to the home poster to another new image poster which you can see down below 2nd image, Even after changing static/image.jpg and replacing it with another image not working, Take a look at this here is what I made changes to style.css while changing the image home poster.

Can you guide me or where to head up to change to my new poster image.

![changes](https://user-images.githubusercontent.com/41158838/130743027-0edf14cc-8acd-4aab-b85c-73ded7f87771.png)
![image 1](https://user-images.githubusercontent.com/41158838/130743031-05cfa219-5395-414b-b915-4f896b0e7607.png)

**Comment by kishan0725** [comment]
Try ctrl+f5 to refresh the page

**Comment by Tharun-tharun** [comment]
> Try ctrl+f5 to refresh the page

Yeah did that too, I did that multiple times by refreshing it, but still getting the same image as the default image of yours still can't get it fixed maybe try it from your end though just by changing to another image.
