### ISSUE TITLE
I changed the api key in recommed.js but after searching I am rerouted to the homepage

### ISSUE THREAD

**Issue by sanyagoyal2000** [kishan0725/The-Movie-Cinema#18]

**Comment by friendlyved** [comment]
same issue If U have Solved The Error Please Tell me

**Comment by Sarveshwarneogi** [comment]
Has anyone solved this issue?

**Comment by AashishA11** [comment]
if anyone solve the issue pls tell how to slove the issue?

**Comment by sanyagoyal2000** [comment]
https://github.com/sanyagoyal2000/cmdb
check this out
