### ISSUE TITLE
After searching a movie, it says "Invalid Request"

### ISSUE THREAD

**Issue by mehantkr** [kishan0725/The-Movie-Cinema#2]
Replaced my api key in both the lines in static/recommend.js
Created vitrualenv, activated it
Installed all the requirements.
ran the server but after searching a movie in the browser, it says "Invalid Request"
It doesn't works.
Can you fix the code

**Comment by kishan0725** [comment]
@mehantkr There's nothing wrong with the code. If you make a request without the API key for the first time, your browser caches the request in the browser memory and throws an `Invalid request` error. Even though you replaced the API key for the subsequent requests, your browser will always make use of the request from the browser cache. What I would suggest is to press `ctrl+f5` (which clears the content of the browser cache) and try making a request.

For more details, please look into this issue #1

**Comment by mehantkr** [comment]
Oh yah... That worked.

**Comment by chithraanil** [comment]
'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application'.Im getting this error after loading from the home page

**Comment by ajaymathur442** [comment]
![error](https://user-images.githubusercontent.com/57529648/123754593-b2d87d80-d8d8-11eb-9bf1-b67f5ab5b5e1.PNG)
error in installing requirments.txt

**Comment by bshweta1901** [comment]
ran the server but after searching a movie in the browser, it says "Invalid Request"
 Invalid Request - [object Object]
It doesn't works.

**Comment by Iprashant91** [comment]
Hey Kishan, 

Thank you very much for such wonderful project, I run this project without any issue because instruction of very clean and clear. 

I want to integrate apache kafka in this project can you help me please.

**Comment by Reshma-123-spec** [comment]
I'm unable to open my pkl file. Its showing utf-8 is not encoded

**Comment by HarshLalwani19** [comment]
after entering a movie it buffers for a while then goes back to the search page again

**Comment by ITSME1516** [comment]
![Screenshot 2023-04-21 173132](https://user-images.githubusercontent.com/127421404/233632653-167f9e11-91e7-4c2d-b6d2-6a20eadc210c.png)
iam getting this kind of error #error recs. say some solution to solve it

**Comment by kishan0725** [comment]
@ITSME1516 Check your terminal or command prompt where you run the Flask app and look for any error/exception

**Comment by ITSME1516** [comment]
its showing some warning bro

**Comment by ITSME1516** [comment]
![Screenshot 2023-04-21 175525](https://user-images.githubusercontent.com/127421404/233634854-cd2433e5-04f3-4fc6-8f22-45a3eecc74e6.png)
its the warning iam getting

**Comment by kishan0725** [comment]
@ITSME1516 It doesn't look like it has any error/exception. Are you sure this screenshot was taken after you got "error recs" in your browser? Keep in mind that restarting the app would clear the error in your terminal.

**Comment by ITSME1516** [comment]
noo

**Comment by ITSME1516** [comment]
in termina there is no error.some debugger is active and its sowing some debugger pin

**Comment by kishan0725** [comment]
Kindly re-install or upgrade the lxml package and try once.

**Comment by ITSME1516** [comment]
okk

**Comment by sreeja008** [comment]
![Screenshot 2024-03-09 170525](https://github.com/kishan0725/The-Movie-Cinema/assets/162796890/d49b6910-6aaa-44c5-8c67-3b0326f6f912)
its showing invalid request

**Comment by Anmol-Shh** [comment]
> ![Screenshot 2023-04-21 175525](https://user-images.githubusercontent.com/127421404/233634854-cd2433e5-04f3-4fc6-8f22-45a3eecc74e6.png) its the warning iam getting

Hi buddy did you got any solution for this? It will be very helpful

**Comment by Anmol-Shh** [comment]
Hi Kishan, 
I’m getting a long string of error consisting of vectorisation error, fitting error. Please fix the code!

**Comment by IMMORTALCHIRU** [comment]
> > ![Screenshot 2023-04-21 175525](https://user-images.githubusercontent.com/127421404/233634854-cd2433e5-04f3-4fc6-8f22-45a3eecc74e6.png) its the warning iam getting
> 
> Hi buddy did you got any solution for this? It will be very helpful

**Nothing to worry about that error it is just showing up due to the model file is trained with `scikit-learn==1.2.1` and in your system you have `scikit-learn==1.2.2` version installed, If you want to train the model file train it with the current interpreter or else install `Python version 3.8.0` and install all the requirements by removing the version specifications of them. It will fix the error for sure.**

**Comment by dakshcoder27** [comment]
> after entering a movie it buffers for a while then goes back to the search page again
buddy did your error got resolved

**Comment by anuska-code** [comment]
![Image](https://github.com/user-attachments/assets/0dc14457-debc-431e-9c5f-90968a47abbc)


hey! the only problem i am having is whenever i click on the picture the details is not showing 

also in home.html file this line of code is showing the error: 

<script type="text/javascript">
    var films = {{suggestions|tojson}};
    $(document).ready(function(){
      $("#myModal").modal('show');
    });
  </script>

**Comment by varshamodi28** [comment]
> ![Image](https://github.com/user-attachments/assets/0dc14457-debc-431e-9c5f-90968a47abbc)
> 
> hey! the only problem i am having is whenever i click on the picture the details is not showing
> 
> also in home.html file this line of code is showing the error:
> 
> <script type="text/javascript"> var films = {{suggestions|tojson}}; $(document).ready(function(){ $("#myModal").modal('show'); }); </script>

gettig a same if this resolve help me

**Comment by anuska-code** [comment]
![Image](https://github.com/user-attachments/assets/afc9080f-fec7-42b3-be8b-196d31104c0f)

@kishan0725  my reviews of users are not being showed,I tried a multiple times still I am facing a problem can you help me here 
please?
