### ISSUE TITLE
Invalid request- Object object

### ISSUE THREAD

**Issue by PremTejaV** [kishan0725/The-Movie-Cinema#3]
![Screenshot (147)](https://user-images.githubusercontent.com/76657145/103756110-e4ad0d80-5034-11eb-8a99-4870690edc67.png)
No ctrl-5 is working in browser

In heroku, Some error and same faults as in browser
![Screenshot (148)](https://user-images.githubusercontent.com/76657145/103756379-49686800-5035-11eb-84b0-af28916b74e8.png)

Please help me!!

**Comment by kishan0725** [comment]
@PremTejaV Ignore the error you're getting in the deployment part. Coming to the "Invalid request", please make sure you have the API key in both the places of the recommend.js file. If you did replace the API key, make sure your request contains the API in the network tab of your browser developer tools. Take a look at this issue #1 for more info.

**Comment by PremTejaV** [comment]
It's working now!!
Thank you
