### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kevalsayar** [kishan0725/The-Movie-Cinema#9]
C:\Users\keval\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator MultinomialNB from version 0.23.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\keval\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.23.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\keval\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.23.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
Nothing is working because of this error. Can you please help solve this at the earliest.

**Comment by kishan0725** [comment]
Looks like it's just a warning and has no effect in the app. See if the app is running perfectly fine in the browser. If you face any issues with running the app, make sure you replace the API key in both the places of the recommend.js file. If that still doesn't help you out, kindly visit the closed issues. Kindly close the issue if it works.

**Comment by kevalsayar** [comment]
It has a effect on the app because the recommendations are not being shown
and it was working fine before but then it's not since that warning.

**Comment by kishan0725** [comment]
"It was working fine before" - I'm not sure why it's not working, and there's nothing to check from my end as it was working fine for you earlier and there has been no new codes commited to the repo. You can track the issue by looking into the browser console. Check if you could see the API key in the network tab.

**Comment by kishan0725** [comment]
Closing this issue as I've not heard anything from you! Reopen the issue if you still need any help. Thanks :)
